### ISSUE TITLE
是不是缺少依赖啊？我npm run watch后有报错

### ISSUE THREAD

**Issue by BaliStarDUT** [zce/weapp-boilerplate#2]
报错如下：有好几个模块都说找不到，一个个安装又太麻烦了。对前端库不是很熟悉，需要修改什么吗？
`james weapp-boilerplate # npm run watch

> weapp-boilerplate@0.1.0 watch /home/james/code/hello-world/code/weixin/weapp-boilerplate
> gulp watch

[15:24:47] Using gulpfile /home/james/code/hello-world/code/weixin/weapp-boilerplate/gulpfile.js
[15:24:47] Starting 'lint'...
[15:24:48] Finished 'lint' after 1.14 s
[15:24:48] Starting 'build'...
[15:24:48] Starting 'clean'...
[15:24:48] Starting 'extras'...
[15:24:48] Finished 'clean' after 15 ms
[15:24:48] Starting 'compile'...
[15:24:48] Starting 'compile:js'...
[15:24:49] 'compile:js' errored after 801 ms
[15:24:49] Error: Cannot find module 'babel-generator'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/james/code/hello-world/code/weixin/weapp-boilerplate/node_modules/.6.23.1@babel-core/lib/transformation/file/index.js:62:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
[15:24:49] 'build' errored after 820 ms
[15:24:49] Error in plugin 'run-sequence(compile:js)'
Message:
    Cannot find module 'babel-generator'
`

**Comment by zce** [comment]
删除 node_modules 目录，重新执行`npm install`，确认没有错误过后再使用`npm run watch`

**Comment by BaliStarDUT** [comment]
解决。确实是这个问题。
